.PHONY: main VD1 VD2 VD3 VD4 VD5 clean
main:
	gcc -o test main.c
VD1:
	gcc -o VD1 VD1.c
VD2:
	gcc -o VD2 VD2.c
VD3:
	gcc -o VD3 VD3.c
VD4:
	gcc -o VD4 VD4.c

VD5:
	gcc -o VD5 VD5.c
clean:
	rm -rf test VD1 VD2 VD3 VD4 VD5

